package com.example.nammafarmer

class SaveSeeds(
    val UniqueID: String,
    val Name: String,
    val Phone: String,
    val EMail: String,
    val Rice: Boolean,
    val Onion: Boolean,
    val Tomato: Boolean,
    val Bendi: Boolean,
    val Brinjal: Boolean,
    val Pumpkin: Boolean,
    val Wheat: Boolean,
    val Karela: Boolean,
    val Beans: Boolean,
    val Carrot: Boolean,
    val Squash: Boolean,
    val Radish: Boolean,
    val Millets: Boolean,
    val Chilli: Boolean,
    val Ginger: Boolean,
    val Garlic: Boolean,
    val Spices: Boolean,
    val Others: Boolean)